=== Javito999/pruebasGit/EjerciciosXML/EjerciciosXML1/dtd/ejercicio1.dtd
<!ELEMENT Mensajeria (pedido*)>
<!ELEMENT pedido (Destinatario, producto+, Dia_entrega)>

<!ELEMENT Destinatario (nombre, direccion)>
<!ATTLIST Destinatario  
            codCliente ID #IMPLIED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT producto (tipo_producto, importe)>
<!ELEMENT tipo_producto (#PCDATA)>
<!ELEMENT importe (#PCDATA)>
<!ELEMENT Dia_entrega (fecha)>
<!ELEMENT fecha (#PCDATA)>

=== Javito999/pruebasGit/EjerciciosXML1/Ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Mensajeria SYSTEM "./dtd/ejercicio1.dtd">
<Mensajeria>

    <pedido>

    <Destinatario codCliente="A5">
        <nombre></nombre>
        <direccion></direccion>
    </Destinatario>

    <producto >
        <tipo_producto></tipo_producto>
        <importe></importe>
    </producto>

    <Dia_entrega>
        <fecha></fecha>
    </Dia_entrega>
    

    </pedido>

</Mensajeria>
